# Generated by Django 2.2.10 on 2020-03-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_kid',
            field=models.BooleanField(default=False),
        ),
    ]
