# Generated by Django 2.2.10 on 2020-03-28 04:17

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_has_kid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True),
        ),
    ]
